name: Go
on: [push]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - name: lint
      run: go install github.com/ysmood/golangci-lint@latest && golangci-lint

    - name: test
      run: |
        go test -race -coverprofile=coverage.out
        go install github.com/ysmood/got/cmd/check-cov@latest && check-cov
